version: "3"
services:
  app:
    image: node:latest
    ports:
      - "8080:8080"
    working_dir: /usr/src/app
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
    tty: true
