version: "3"
services:
  app:
    image: node:latest
    ports:
      - "3000:3000"
    working_dir: /usr/src/app/my-app
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
    tty: true